# Generated by Django 5.1.5 on 2025-02-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        ("comment", "0002_alter_comment_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="board.board",
            ),
        ),
    ]
